chore: Bring release pipelines up to date with keptn/keptn (#403)

diff --git a/.github/workflows/pre-release.yml b/.github/workflows/pre-release.yml
--- a/.github/workflows/pre-release.yml
+++ b/.github/workflows/pre-release.yml
@@ -1,8 +1,12 @@
 name: Pre-Release
 on:
   workflow_dispatch:
+    inputs:
+      semver-type:
+        description: 'Can be one of [major,minor,patch]. CAUTION: This will enforce a new pre-release with the specified semantic version type bumped.'
+        required: false
 env:
-  NODE_VERSION: 14
+  NODE_VERSION: 16
   KEPTN_BOT_NAME: "Keptn Bot"
   KEPTN_BOT_EMAIL: "keptn-bot <86361500+keptn-bot@users.noreply.github.com>"
   RELEASE_NOTES_FILE: "RELEASE-BODY.md"
@@ -11,11 +15,70 @@ defaults:
   run:
     shell: bash
 jobs:
+  prepare:
+    name: Prepare release run
+    runs-on: ubuntu-20.04
+    outputs:
+      next-version: ${{ steps.version_number.outputs.next-version }}
+      branch: ${{ steps.current_branch.outputs.branch }}
+    steps:
+      - name: Check SemVer input
+        env:
+          SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
+        run: |
+          if [[ ! -z "$SEMVER_TYPE" ]]; then
+            echo "SemVer Type is defined. Checking for valid SemVer type..."
+            if [[ "$SEMVER_TYPE" == "major" ]] || [[ "$SEMVER_TYPE" == "minor" ]] || [[ "$SEMVER_TYPE" == "patch" ]]; then
+              echo "::notice::SemVer Type is correctly set to $SEMVER_TYPE! Continuing with this version bump..."
+            else
+              echo "::error::ERROR: Enforced SemVer does not match any of [major,minor,patch]!"
+              echo "Exiting..."
+              exit 1
+            fi
+          else
+            echo "::notice::No SemVer type defined, continuing with auto generated version number..."
+          fi
+
+      - name: Checkout repo
+        uses: actions/checkout@v2.4.0
+        with:
+          fetch-depth: 0
+
+      - name: Find next version number
+        id: version_number
+        env:
+          SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
+        run: |
+          if [[ ! -z "$SEMVER_TYPE" ]]; then
+            npx standard-version@^9.3.1 \
+              --skip.commit \
+              --skip.tag \
+              --skip.changelog \
+              --prerelease "${{ env.PRERELEASE_KEYWORD }}" \
+              --release-as "$SEMVER_TYPE"
+          else
+            npx standard-version@^9.3.1 \
+              --skip.commit \
+              --skip.tag \
+              --skip.changelog \
+              --prerelease "${{ env.PRERELEASE_KEYWORD }}"
+          fi
+
+          NEXT_VERSION=$(cat VERSION.txt)
+          echo "::set-output name=next-version::${NEXT_VERSION}"
+          git checkout HEAD -- VERSION.txt
+
+      - name: Find current branch
+        id: current_branch
+        run: |
+          branch=${GITHUB_REF#refs/heads/}
+          echo "::set-output name=branch::${branch}"
   test:
+    needs: prepare
     strategy:
       matrix:
-        go-version: [1.16.x]
-        platform: [ubuntu-latest]
+        go-version: [ 1.16.x ]
+        platform: [ ubuntu-latest ]
     runs-on: ${{ matrix.platform }}
     env:
       GO111MODULE: "on"
@@ -26,22 +89,22 @@ jobs:
         with:
           go-version: ${{ matrix.go-version }}
       - name: Checkout code
-        uses: actions/checkout@v2.3.4
+        uses: actions/checkout@v2.4.0
       - name: Test
         run: go test -race -v ./...
   pre-release:
-    name: Pre-Release
+    name: "Pre-Release"
     runs-on: ubuntu-20.04
-    needs: [test]
+    needs: [ prepare, test ]
     steps:
       - name: Checkout repo
-        uses: actions/checkout@v2
+        uses: actions/checkout@v2.4.0
         with:
           fetch-depth: 0
           token: ${{ secrets.KEPTN_BOT_TOKEN }}
 
       - name: Set up Node.js
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v2.5.1
         with:
           node-version: ${{ env.NODE_VERSION }}
 
@@ -53,9 +116,26 @@ jobs:
           git config user.name "$KEPTN_BOT_NAME"
           git config user.email "$KEPTN_BOT_EMAIL"
 
-      - name: Prepare GitHub Release Notes
+      - name: Prepare GitHub Pre-Release Notes
+        env:
+          SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
         run: |
-          npx standard-version@^9.3.1 --prerelease "${{ env.PRERELEASE_KEYWORD }}" -i "${{ env.RELEASE_NOTES_FILE }}" --skip.commit --skip.tag --header ""
+          if [[ ! -z "$SEMVER_TYPE" ]]; then
+            npx standard-version@^9.3.1 \
+              --prerelease "${{ env.PRERELEASE_KEYWORD }}" \
+              -i "${{ env.RELEASE_NOTES_FILE }}" \
+              --skip.commit \
+              --skip.tag \
+              --header "" \
+              --release-as "$SEMVER_TYPE"
+          else
+            npx standard-version@^9.3.1 \
+              --prerelease "${{ env.PRERELEASE_KEYWORD }}" \
+              -i "${{ env.RELEASE_NOTES_FILE }}" \
+              --skip.commit \
+              --skip.tag \
+              --header ""
+          fi
 
       - name: Enhance Release Notes with Build Metadata
         run: |
@@ -66,16 +146,30 @@ jobs:
       - name: Create pre-release package
         id: create-release-package
         env:
+          SEMVER_TYPE: ${{ github.event.inputs.semver-type }}
           GITHUB_TOKEN: ${{ secrets.KEPTN_BOT_TOKEN }}
         run: |
           echo "🚀 Creating pre-release package now..."
-          npx standard-version@^9.3.1 --prerelease "${{ env.PRERELEASE_KEYWORD }}" --skip.commit --skip.changelog
+
+          if [[ ! -z "$SEMVER_TYPE" ]]; then
+            npx standard-version@^9.3.1 \
+              --release-as "$SEMVER_TYPE" \
+              --prerelease "${{ env.PRERELEASE_KEYWORD }}" \
+              --skip.commit \
+              --skip.changelog
+          else
+            npx standard-version@^9.3.1 \
+              --prerelease "${{ env.PRERELEASE_KEYWORD }}" \
+              --skip.commit \
+              --skip.changelog
+          fi
 
           echo "::set-output name=tag-name::$(git describe --tags --abbrev=0)"
+
           echo "⚡️ Pushing changes to remote repository..."
           git push --follow-tags
 
-      - name: Create GitHub Release
+      - name: Create GitHub Pre-Release
         env:
           GITHUB_TOKEN: ${{ secrets.KEPTN_BOT_TOKEN }}
           RELEASE_TAG: ${{ steps.create-release-package.outputs.tag-name }}
